### ISSUE TITLE
BUG: Windows 10 installation error

### ISSUE THREAD

**Issue by rkmaddox** [mrkrd/cochlea#10]
Hi there,

I am am trying to install with standard pip command and getting an error that Microsoft Visual C++ 14.0 is required. This seems like an issue for two reasons: I have MS Build Tools installed (version 15), and from the installation instructions it sounds like I should be able to get binaries and there shouldn't be any need to build anyway.

Thanks for any guidance (and for maintaining this extremely useful tool!).

**Comment by rkmaddox** [comment]
I should add that I am using Anaconda 3 on Windows 10.

**Comment by mrkrd** [comment]
> I am am trying to install with standard pip command and getting an
> error that Microsoft Visual C++ 14.0 is required. This seems like an
> issue for two reasons: I have MS Build Tools installed (version 15),

From what I remember, the correct version is quite important.  It need
to be the same version of MS Build Tools that was used to build Python
itself.

BTW, which Python version are you using?


> and from the installation instructions it sounds like I should be able
> to get binaries and there shouldn't be any need to build anyway.

There's a pre-build binary package for Python 2.7.

**Comment by rkmaddox** [comment]
Ahh interesting. My understanding was that MS build tools would be backwards compatible. I am using python 3, so that would be why there was no binary. I'll give building it myself a go and let you know if I make progress or not.

**Comment by rkmaddox** [comment]
It seems I have many versions installed, which out to cover 14.0:
![image](https://user-images.githubusercontent.com/3029642/77924172-5e77c580-7271-11ea-9dac-ab7c7f1abdfc.png)
The list actually goes back to 2008.

I tried install Build Tools 2015 (which doesn't have a version number, but 2017 was version 15 and 2019 was version 16, so it is probably 14?)

Sorry, this stuff is not a strength of mine... I now have my Linux computer taken home, so I may just switch to working on that rather than my Windows laptop, but I'd still like to get it working if possible.

**Comment by rkmaddox** [comment]
The exact error is: `error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/`

**Comment by mrkrd** [comment]
Sorry, but I'll not be able to help you with Windows, because I have no
Windows computer myself.

I compiled cochlea for Windows in the past.  You can find instructions
and a build script here:
https://github.com/mrkrd/cochlea/blob/master/INSTALL.rst#installation-from-source-code-on-windows

**Comment by rkmaddox** [comment]
Fair enough. I'll be back to doing it on linux again soon.
