### ISSUE TITLE
AttributeError: module 'cochlea.stats' has no attribute 'calc_rate_intensity'

### ISSUE THREAD

**Issue by SchraivogelS** [mrkrd/cochlea#14]
https://github.com/mrkrd/cochlea/blob/f4f9734f07a6792eac14d10eae0dd30224209bb8/examples/cochlea_demo.ipynb?short_path=b9f3970#L256

Call 'calc_rate_level' instead to resolve the issue

cochlea==2

**Comment by mrkrd** [comment]
done
