### ISSUE TITLE
Problems importing _pycat?

### ISSUE THREAD

**Issue by gvoysey** [mrkrd/cochlea#2]
First, thanks for this!  I saw the announcement come across the auditory list, and have gotten the time to check it out.  (Greetings from BU!)

I'm running into what is probably a configuration issue, so my apologies for what may be a stupid question. 

I've set up anaconda 32-bit on a windows 7 x64 box, running python 2.7.x.   I'm running cochlea under the debugger, using PyCharm as my IDE.   I've cloned both `cochlea` and `thorns`, and they reside in `C:/Projects/cochlea`

Running `examples\run_zilany2014.py` results in the following: 

```
"C:\Users\gvoysey\Anaconda\python.exe" C:/Projects/cochlea/cochlea/examples/run_zilany2014_rate.py
Traceback (most recent call last):
File "C:/Projects/cochlea/cochlea/examples/run_zilany2014_rate.py", line 42, in <module>
     import cochlea
File "C:\Projects\cochlea\cochlea\cochlea\__init__.py", line 30, in <module>
from cochlea.zilany2009 import run_zilany2009
File "C:\Projects\cochlea\cochlea\cochlea\zilany2009\__init__.py", line 28, in <module>
from . import _pycat
ImportError: cannot import name _pycat
```

I'm not sure why this may be.  Any thoughts?

**Comment by Huitzilo** [comment]
I know I risk waking a zombie here, however I ran into the same issue trying to run `cochlea` on macOS. I first built from source and received the above error that the `_pycat` could not be found.
Installing from pip didn't resolve the issue. 
Digging a bit deeper I found that `_pycat.so` is present in `build/lib.macosx-10.6-x86_64-2.7/`, but somehow the build process doesn't seem to copy it over to the target directory.

**Comment by mrkrd** [comment]
> I know I risk waking a zombie here, however I ran into the same issue trying to run `cochlea` on macOS. I first built from source and received the above error that the `_pycat` could not be found.
> Installing from pip didn't resolve the issue. 
> Digging a bit deeper I found that `_pycat.so` is present in `build/lib.macosx-10.6-x86_64-2.7/`, but somehow the build process doesn't seem to copy it over to the target directory. 

It's a bit hard to guess what might be the issue here.  You could:

1. Try to find a hint in the log/output generated by pip.

2. Install *cochlea* using “python setup.py develop --user”

   https://github.com/mrkrd/cochlea/blob/master/INSTALL.rst#installation-from-source-code

**Comment by Huitzilo** [comment]
There are no hints in the output of `setup.py install`. It simply ignores `_pycat.so`.
`python setup.py develop` works, thank you for the workaround.
