### ISSUE TITLE
ffGn function bug?

### ISSUE THREAD

**Issue by nasiryahm** [mrkrd/cochlea#4]
I am attempting to write a high speed version of the Zilany 2014 model. I noticed an inconsistency in the /cochlea/zilany2014/utils.py file.

The ffGn function calculates the fGN @ line 73 for H == 0.5. However, the return statement (which returns y) is only present in the else statement. In the case of (H == 0.5), the ffGn function would not return an array?

Although, digging through the code it seems that (in both the cochlea and original Zilany model) H will be hardcoded at 0.9 for this simulation.

Hope this helps.

--Nas

**Comment by mrkrd** [comment]
> I am attempting to write a high speed version of the Zilany 2014
> model. I noticed an inconsistency in the /cochlea/zilany2014/utils.py
> file.
>
> The ffGn function calculates the fGN @ line 73 for H == 0.5. However,
> the return statement (which returns y) is only present in the else
> statement. In the case of (H == 0.5), the ffGn function would not
> return an array?
>
> Although, digging through the code it seems that (in both the cochlea
> and original Zilany model) H will be hardcoded at 0.9 for this
> simulation.

Yes, ASAIK this path is never reached.

When transcribing this code from MATLAB my goal was to be as close to
the original as possible.  I wanted to have exactly the same results
numerically (one of the primary goals of *cochlea*).  I also did not
mind to copy some small wired stuff like this, to simplify porting of
the code in the future versions of the original model.

I'll close this issue for now, but you can submit a PR that fixes it, if
you need it.  In this case, please make sure that the default behavior
is the same as in original implementation and try to reasonably close to
the MATLAB implementation (for easier maintenance).

PS How do you plan to speed up the model?  What are the hot spots
currently?

(close #4)

**Comment by nasiryahm** [comment]
True, the path is not reached. This perhaps did not warrant an issue, apologies.

From what I have observed while profiling the python code, the IHCAN C function is the slowest part of the model (under certain running conditions taking 90% of the processing time). I am considering profiling that code and either addressing any bottlenecks or potentially writing a CUDA implementation. Unfortunately, I do not have the time and the CUDA implementation might not deal well with double precision (at least on my hardware) so I shall think hard before continuing.

Thanks for producing this package, it has been invaluable to my research!

**Comment by mrkrd** [comment]
> True, the path is not reached. This perhaps did not warrant an issue, apologies.

No problem, actually it's great to use GH issue tracker to answer
questions, because other people might find them useful too.


> From what I have observed while profiling the python code, the IHCAN C
> function is the slowest part of the model (under certain running
> conditions taking 90% of the processing time). I am considering
> profiling that code and either addressing any bottlenecks or
> potentially writing a CUDA implementation. Unfortunately, I do not
> have the time and the CUDA implementation might not deal well with
> double precision (at least on my hardware) so I shall think hard
> before continuing.

I'll not be able to help, because I do not know the C implementation
well enough to optimize it for speed.


> Thanks for producing this package, it has been invaluable to my research!

I'm happy to hear that, thanks!


BTW, how do you install the package and which OS do you use?

**Comment by nasiryahm** [comment]
I have been installing in python via pip using the cochlea package on both OS X (10.10 and 10.11) and on Ubuntu 16.04. I have also installed on OS X 10.12 (beta) by pulling from master. Do you recommend always pulling from master? Or is the pypi version generally up to date?

**Comment by mrkrd** [comment]
> I have been installing in python via pip using the cochlea package on
> both OS X (10.10 and 10.11) and on Ubuntu 16.04. I have also installed
> on OS X 10.12 (beta) by pulling from master.

Cool, thanks!


> Do you recommend always
> pulling from master? Or is the pypi version generally up to date?

Master is the safest bet, but I generally I always update PyPI whenever
there's a significant change.
